Repository osate/osate2, pull requests merged in 2018-06, with the labels that each got.

#1283 IGlobalScopeProvider enhancement
  core/org.osate.ui/src/org/osate/ui/wizards/AbstractNewModelUnitWizard.xtend
  core/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/scoping/Aadl2GlobalScopeProvider.java
  core/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation/Aadl2JavaValidator.java
  emv2/org.osate.xtext.aadl2.errormodel/src/org/osate/xtext/aadl2/errormodel/ErrorModelRuntimeModule.java
Labels: review

#1282 Add a method to instantiate without saving to a file
  core/org.osate.aadl2.instantiation/src/org/osate/aadl2/instantiation/InstantiateModel.java
Labels: review

#1285 1268 move emv2 parser linker
  emv2/org.osate.xtext.aadl2.errormodel.ui/META-INF/MANIFEST.MF
  emv2/org.osate.xtext.aadl2.errormodel.ui/src/org/osate/xtext/aadl2/errormodel/parsing/EMV2AnnexUnparser.xtend
  emv2/org.osate.xtext.aadl2.errormodel/META-INF/MANIFEST.MF
  emv2/org.osate.xtext.aadl2.errormodel/src/org/osate/xtext/aadl2/errormodel/parsing/EMV2AnnexLinkingService.java
  emv2/org.osate.xtext.aadl2.errormodel/src/org/osate/xtext/aadl2/errormodel/parsing/EMV2AnnexParser.java
  emv2/org.osate.xtext.aadl2.errormodel/src/org/osate/xtext/aadl2/errormodel/parsing/EMV2AnnexUnparser.java
Labels: review

#1286 1275 return value assignment
  alisa/org.osate.alisa.help/help/markdown/VerifyDoc.md
  alisa/org.osate.assure/src/org/osate/assure/evaluator/AssureProcessor.xtend
  alisa/org.osate.verify/src/org/osate/verify/util/VerifyUtilExtension.xtend
Labels: review

#1287 Fixes 1276
  alisa/org.osate.assure/src/org/osate/assure/evaluator/AssureProcessor.xtend
Labels: review

#1290 1279 handle no matching results from plugin analysis
  alisa/org.osate.assure/src/org/osate/assure/evaluator/AssureProcessor.xtend
Labels: review

#1295 Added version requirement for ELK dependencies.
  core/org.osate.build.product/osate.product
  ge/org.osate.ge/META-INF/MANIFEST.MF
Labels: ge, review

#1294 1293 optional resolute agree dependency
  alisa/org.osate.alisa.workbench/META-INF/MANIFEST.MF
  alisa/org.osate.assure/META-INF/MANIFEST.MF
  alisa/org.osate.assure/src/org/osate/assure/util/ExecuteResoluteUtil.java
  alisa/org.osate.verify.ui/META-INF/MANIFEST.MF
  alisa/org.osate.verify/META-INF/MANIFEST.MF
  emv2/org.osate.aadl2.errormodel.propagationgraph/META-INF/MANIFEST.MF
Labels: review

#1298 Add instantiation methods that return errors and don't save the model
  core/org.osate.aadl2.instantiation/src/org/osate/aadl2/instantiation/InstantiateModel.java
Labels: review

#1303 #1300 Extra disgnostics in Resolute result presentation in ALISA
  alisa/org.osate.assure/src/org/osate/assure/evaluator/AssureProcessor.xtend
  alisa/org.osate.assure/src/org/osate/assure/util/ExecuteResoluteUtil.java
Labels: review

#1308 Graphical Editor Memory Leak Fixes
  ge/org.osate.ge/src/org/osate/ge/internal/ui/editor/AgeDiagramBehavior.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/editor/GraphitiEditPartAdapterFactory.java
Labels: ge, review

#1304 #1301 Use qualified Resolute claim or compute function name in verify method registry
  alisa/org.osate.alisa.help/help/markdown/SystemVerificationGuidance.md
  alisa/org.osate.alisa.help/help/markdown/VerifyDoc.md
  alisa/org.osate.verify.ui/src-gen/org/osate/verify/ui/contentassist/antlr/internal/InternalVerify.g
  alisa/org.osate.verify.ui/src-gen/org/osate/verify/ui/contentassist/antlr/internal/InternalVerifyParser.java
  alisa/org.osate.verify/src-gen/org/osate/verify/Verify.xtextbin
  alisa/org.osate.verify/src-gen/org/osate/verify/parser/antlr/internal/InternalVerify.g
  alisa/org.osate.verify/src-gen/org/osate/verify/parser/antlr/internal/InternalVerifyLexer.java
  alisa/org.osate.verify/src-gen/org/osate/verify/parser/antlr/internal/InternalVerifyParser.java
  alisa/org.osate.verify/src-gen/org/osate/verify/serializer/VerifySemanticSequencer.java
  alisa/org.osate.verify/src-gen/org/osate/verify/services/VerifyGrammarAccess.java
  alisa/org.osate.verify/src/org/osate/verify/Verify.xtext
  alisa/org.osate.verify/src/org/osate/verify/linking/VerifyLinkingService.java
Labels: review

#1314 Provide a global scope utility class that looks up AADL elements by meta class and name
  core/org.osate.aadl2.modelsupport/META-INF/MANIFEST.MF
  core/org.osate.aadl2.modelsupport/src/org/osate/aadl2/modelsupport/scoping/Aadl2GlobalScopeUtil.java
  core/org.osate.aadl2.modelsupport/src/org/osate/aadl2/modelsupport/scoping/EClassGlobalScopeProvider.java
  core/org.osate.aadl2.modelsupport/src/org/osate/aadl2/modelsupport/scoping/IEClassGlobalScopeProvider.java
  core/org.osate.xtext.aadl2.properties.ui/src/org/osate/xtext/aadl2/properties/ui/quickfix/PropertiesQuickfixProvider.xtend
  core/org.osate.xtext.aadl2.properties/src/org/osate/xtext/aadl2/properties/util/GetProperties.java
  core/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/scoping/Aadl2GlobalScopeProvider.java
Labels: review

#1306 Flow analysis parameters
  analyses/org.osate.analysis.flows.tests/src/org/osate/analysis/flows/tests/CombinedETEFTest.xtend
  analyses/org.osate.analysis.flows.tests/src/org/osate/analysis/flows/tests/FlowLatencyTest.xtend
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/FlowLatencyAnalysisSwitch.java
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/handlers/CheckFlowLatency.java
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/model/LatencyContributor.java
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/model/LatencyContributorComponent.java
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/model/LatencyContributorConnection.java
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/model/LatencyReport.java
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/model/LatencyReportEntry.java
  analyses/org.osate.analysis.flows/src/org/osate/analysis/flows/preferences/Values.java
Labels: review

#1292 Use shared resource set for tests
  core/org.osate.aadl2.instantiation/src/org/osate/aadl2/instantiation/InstantiateModel.java
  core/org.osate.aadl2.modelsupport/src/org/osate/aadl2/modelsupport/resources/OsateResourceUtil.java
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2scopeprovider/ModeTransitionsTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue1092Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue277Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue361Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue448Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue464Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue480Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue500Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue508Test.xtend
  core/org.osate.testsupport/META-INF/MANIFEST.MF
  core/org.osate.testsupport/src/org/osate/testsupport/Aadl2InjectorProvider.java
  core/org.osate.testsupport/src/org/osate/testsupport/AssertHelper.xtend
  core/org.osate.testsupport/src/org/osate/testsupport/OsateTest.xtend
  core/org.osate.testsupport/src/org/osate/testsupport/TestHelper.java
  core/org.osate.testsupport/src/org/osate/testsupport/TestResourceSetHelper.java
  core/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/parsing/AnnexParserAgent.java
  emv2/org.osate.aadl2.errormodel.tests/src/org/osate/aadl2/errormodel/tests/issues/Issue53Test.xtend
  emv2/org.osate.xtext.aadl2.errormodel.ui/plugin.xml
  emv2/org.osate.xtext.aadl2.errormodel/plugin.xml
Labels: review

#1318 1291 migrate tests
  core/org.osate.core.tests/src/org/osate/core/tests/ParserTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/PropertyTests.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/ScopeTests.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2javavalidator/ConnectionAndFlowTypesTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2javavalidator/DataSizePropertyTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2javavalidator/EndToEndFlowSegmentTypesTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2javavalidator/FeatureGroupChainingTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2javavalidator/OtherAadl2JavaValidatorTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2scopeprovider/ConnectedElementsAndFlowEndsTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2scopeprovider/FeaturesAndSubcomponentsTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2scopeprovider/FlowSegmentsTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2scopeprovider/OtherAadl2ScopeProviderTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/aadl2scopeprovider/PropertySetReferencesTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/formatter/FormatterTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/propertiesjavavalidator/PropertiesJavaValidatorTest.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/propertiesscopeprovider/PropertiesScopeProviderTest.xtend
Labels: review

#1344 Fixed issues with graphical editor user guide.
  ge/org.osate.ge.doc/docs-gen/user_guide.html
  ge/org.osate.ge.doc/docs-gen/user_guide_toc.xml
  ge/org.osate.ge.doc/docs/user_guide.md
Labels: ge, review

#1343 Removed GitLab CI configuration for graphical editor.
  ge/gitlab-ci/.gitlab-ci.yml
  ge/gitlab-ci/prepare_to_run_tests.py
Labels: ge, review

#1338 Cleanup GE plugin.xml and fix tab sorting.
  ge/org.osate.ge/plugin.xml
Labels: ge, review

#1349 Fix occasional graphical editor exceptions on shutdown.
  ge/org.osate.ge/src/org/osate/ge/internal/selection/AgeBusinessObjectSelectionAdapterFactory.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/properties/AppearancePropertySection.java
Labels: category:bug, ge, review

#1350 Prevents creation of unneeded with statements in graphical editor.
  ge/org.osate.ge/src/org/osate/ge/internal/businessObjectHandlers/SubprogramCallHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/businessObjectHandlers/SubprogramCallSequenceHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/properties/SetExtendedClassifierPropertySection.java
  ge/org.osate.ge/src/org/osate/ge/internal/util/AadlHelper.java
  ge/org.osate.ge/src/org/osate/ge/internal/util/AadlImportsUtil.java
Labels: ge, review

#1351 Fix selection handling to use the current active selection.
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/AgeHandlerUtil.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/AlignBottomHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/AlignCenterHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/AlignLeftHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/AlignMiddleHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/AlignRightHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/AlignTopHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/ArrangeInCircleHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/ArrangeInGridHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/ConfigureDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/CreateDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/CreateNewDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/DeleteHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/DistributeHorizontallyHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/DistributeVerticallyHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/GoToAadlSourceHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/GoToImplementationDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/GoToPackageDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/GoToTypeDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/HideAllContentsHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/InstantiateHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/LayoutContentsHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/MatchHeightHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/MatchSizeHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/MatchWidthHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/OpenAssociatedDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/OpenDiagramHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/RenameHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/SelectContainerHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/SetDescendantsToAutomaticHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/ToggleAllFiltersHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/ToggleContentFilterHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/util/SelectionUtil.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/util/UiUtil.java
Labels: ge, review

#1353 Fix warnings regarding conflicting key bindings.
  core/org.osate.xtext.aadl2.ui/plugin.xml
  ge/org.osate.ge/plugin.xml
  ge/org.osate.ge/src/org/osate/ge/internal/ui/editor/AgeDiagramBehavior.java
Labels: ge, review

#1355 Add commands to make is easier to remove bendpoints from connections.
  ge/org.osate.ge.doc/docs-gen/user_guide.html
  ge/org.osate.ge.doc/docs-gen/user_guide_toc.xml
  ge/org.osate.ge.doc/docs/user_guide.md
  ge/org.osate.ge.doc/images/layout_menu.png
  ge/org.osate.ge/plugin.xml
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/RemoveBendpointsHandler.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/SelectAllConnectionsHandler.java
Labels: ge, review

#1348 Prevent deleting multiple annex shapes to avoid errors.
  ge/org.osate.ge/src/org/osate/ge/internal/graphiti/features/BoHandlerDeleteFeature.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/DeleteHandler.java
Labels: ge, review

#1356 Allow setting extended classifier to none.
  ge/org.osate.ge/src/org/osate/ge/internal/ui/properties/SetExtendedClassifierPropertySection.java
Labels: ge, review

#1358 Reworked DeleteHandler to group elements by resource.
  ge/org.osate.ge/src/org/osate/ge/internal/graphiti/AgeFeatureProvider.java
  ge/org.osate.ge/src/org/osate/ge/internal/graphiti/features/BoHandlerDeleteFeature.java
  ge/org.osate.ge/src/org/osate/ge/internal/ui/handlers/DeleteHandler.java
Labels: ge, review

#1325 Fixes #1323
  alisa/org.osate.assure/src/org/osate/assure/generator/AssureConstructor.xtend
Labels: review

#1326 1324 error icon color
  alisa/org.osate.assure.ui/icons/error.png
  alisa/org.osate.assure.ui/src/org/osate/assure/ui/labeling/AssureLabelProvider.xtend
  alisa/org.osate.assure.ui/src/org/osate/assure/ui/views/AlisaView.xtend
Labels: review

#1330 Fixes issue #1329 skipping resolute compute function result
  alisa/org.osate.assure/src/org/osate/assure/evaluator/AssureProcessor.xtend
  alisa/org.osate.assure/src/org/osate/assure/util/ExecuteResoluteUtil.java
Labels: review

#1333 Fixes refresh issue.
  alisa/org.osate.assure.ui/src/org/osate/assure/ui/views/AlisaView.xtend
Labels: review

#1334 Fixes 1331. Fixes null pointer exception in the middle of editing.
  alisa/org.osate.assure/src/org/osate/assure/util/AssureUtilExtension.xtend
Labels: review

#1320 Don't rebuild contributed AADL on each file save.
  core/org.osate.xtext.aadl2.properties.ui/src/org/osate/xtext/aadl2/properties/ui/builder/PropertiesToBeBuiltComputerContribution.xtend
Labels: review

#1363 1302 resolute qualified name in emv2 condition
  emv2/org.osate.aadl2.errormodel.propagationgraph/META-INF/MANIFEST.MF
  emv2/org.osate.aadl2.errormodel.propagationgraph/src/org/osate/aadl2/errormodel/PropagationGraph/util/ExecuteResoluteUtil.java
  emv2/org.osate.aadl2.errormodel.propagationgraph/src/org/osate/aadl2/errormodel/PropagationGraph/util/Util.java
  emv2/org.osate.xtext.aadl2.errormodel.ui/src-gen/org/osate/xtext/aadl2/errormodel/ui/contentassist/AbstractErrorModelProposalProvider.java
  emv2/org.osate.xtext.aadl2.errormodel.ui/src-gen/org/osate/xtext/aadl2/errormodel/ui/contentassist/antlr/ErrorModelParser.java
  emv2/org.osate.xtext.aadl2.errormodel.ui/src-gen/org/osate/xtext/aadl2/errormodel/ui/contentassist/antlr/internal/InternalErrorModelParser.g
  emv2/org.osate.xtext.aadl2.errormodel.ui/src-gen/org/osate/xtext/aadl2/errormodel/ui/contentassist/antlr/internal/InternalErrorModelParser.java
  emv2/org.osate.xtext.aadl2.errormodel/model/generated/ErrorModel.ecore
  emv2/org.osate.xtext.aadl2.errormodel/model/generated/ErrorModel.genmodel
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/ErrorModel.xtextbin
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/ErrorEvent.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/ErrorFlow.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/ErrorModelFactory.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/ErrorModelPackage.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/IfCondition.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/RecoverEvent.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/impl/ErrorEventImpl.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/impl/ErrorFlowImpl.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/impl/ErrorModelFactoryImpl.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/impl/ErrorModelPackageImpl.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/impl/IfConditionImpl.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/impl/RecoverEventImpl.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/util/ErrorModelAdapterFactory.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/errorModel/util/ErrorModelSwitch.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/parser/antlr/internal/InternalErrorModelParser.g
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/parser/antlr/internal/InternalErrorModelParser.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/serializer/AbstractErrorModelSemanticSequencer.java
  emv2/org.osate.xtext.aadl2.errormodel/src-gen/org/osate/xtext/aadl2/errormodel/services/ErrorModelGrammarAccess.java
  emv2/org.osate.xtext.aadl2.errormodel/src/org/osate/xtext/aadl2/errormodel/ErrorModel.xtext
Labels: review

#1364 Migrated tests
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue766Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue780Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue781Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue789Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue794Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue810Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue815Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue818Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue833Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue835Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue879Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue883Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue910Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue911Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue923Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue929Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue931Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue961Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue986Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue994Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Subset1Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Subset2Test.xtend
Labels: review

#1369 1291 migrate tests sam
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue539Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue560Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue565Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue567Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue575Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue578Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue635Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue636Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue662Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue666Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue699Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue702Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue709Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue718Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue727Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue734Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue736Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue744Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue753Test.xtend
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue761Test.xtend
Labels: review

#1368 1234 fix error message
  core/org.osate.core.tests/models/issue1234/.gitignore
  core/org.osate.core.tests/models/issue1234/.project
  core/org.osate.core.tests/models/issue1234/issue1234.aadl
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue1234Test.xtend
  core/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation/Aadl2JavaValidator.java
Labels: review

#1370 Move unhandled faults
  core/org.osate.ui/plugin.xml
  emv2/org.osate.aadl2.errormodel.analysis/plugin.xml
Labels: review

#1367 1233 validate direction constraint
  core/org.osate.core.tests/models/issue1233/.gitignore
  core/org.osate.core.tests/models/issue1233/.project
  core/org.osate.core.tests/models/issue1233/issue1233.aadl
  core/org.osate.core.tests/src/org/osate/core/tests/issues/Issue1233Test.xtend
  core/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation/Aadl2JavaValidator.java
Labels: review
